### ISSUE TITLE
What's the difference to `new DateTimeImmutable()'

### ISSUE THREAD

**Issue by heiglandreas** [remorhaz/microclock#1]
Hey there.

I currently try to understand the difference between the implementation in https://github.com/remorhaz/microclock/blob/main/src/MicroClock.php#L34-L41 and the following implementation:

```php
public function now(): DateTimeImmutable
{
    return new DateTimeImmutable();
}
```

resp. 

```php
public function __construct(private ?DateTimeImmutable $fixedDate = null) {}

public function now(): DateTimeImmutable
{
    if ($this->fixedDate instanceof DateTimeImmutable) {
        return $this->fixedDate;
    }

    return new DateTimeImmutable();
}
```

Background is that IIRC `DateTimeImmutable` already uses microtime when instantiated. Also `new DateTimeImmutable('2021-09-09 12:03:10.892034');` works to add Microseconds.

**Comment by remorhaz** [comment]
Probably there's no practical reason, you're right. But some time ago there were problems with microseconds, and I've just moved historical code to the repo without checking if old behavior was fixed. My bad )

**Comment by heiglandreas** [comment]
Na. Nothing bad. I was just curious whether I had overseen something :wink:

Every implementation that works is valid!

**Comment by remorhaz** [comment]
I think I will delete it later, though ) It may confuse someone.
